### ISSUE TITLE
Installing pyqt5 makes tests to fail on pydantic_controller branch

### ISSUE THREAD

**Issue by sapetnioc** [populse/soma-base#22]
How to reproduce using a virtualenv and latest Python in a Singularity container:
```
singularity pull --disable-cache python docker://python
git clone -b pydantic_controller https://github.com/populse/soma-base
./python python -m venv venv
./python venv/bin/pip install -e soma-base
./python venv/bin/python -m soma.tests
./python venv/bin/pip install pyqt5
./python venv/bin/python -m soma.tests
```
The first tests are passing but after `pyqt5` installation, I get the following error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/soma-base/python/soma/tests/__main__.py", line 5, in <module>
    test_soma_base.is_valid_module()
  File "/tmp/soma-base/python/soma/tests/test_soma_base.py", line 61, in is_valid_module
    is_valid = run_all_tests()
  File "/tmp/soma-base/python/soma/tests/test_soma_base.py", line 50, in run_all_tests
    tests = load_pilots(module_path, module_path)
  File "/tmp/soma-base/python/soma/tests/load_pilots.py", line 32, in load_pilots
    sub_pilots = load_pilots(root, os.path.join(path, fname))
  File "/tmp/soma-base/python/soma/tests/load_pilots.py", line 48, in load_pilots
    __import__(module_name)
  File "/tmp/soma-base/python/soma/tests/test_qtgui.py", line 9, in <module>
    from soma.qt_gui import controller
  File "/tmp/soma-base/python/soma/qt_gui/controller/__init__.py", line 8, in <module>
    from ..collapsable import CollapsableWidget
  File "/tmp/soma-base/python/soma/qt_gui/collapsable.py", line 6, in <module>
    class CollapsableWidget(Qt.QWidget):
AttributeError: module 'PyQt5.Qt' has no attribute 'QWidget'
```

**Comment by sapetnioc** [comment]
This error comes from PyQt5 not being able to load all of its modules due to container usage and OpenGL library that was not available. On my laptop (with an NVidia graphic card), I need to ask Singularity to to the right things with OpenGL with the `--nv` option whenever PyQt is involved. My example can be modified to work with PyQt5 :

```
singularity pull --disable-cache python docker://python
git clone -b pydantic_controller https://github.com/populse/soma-base
./python python -m venv venv
./python venv/bin/pip install -e soma-base
./python venv/bin/python -m soma.tests
./python venv/bin/pip install pyqt5
singularity run --nv  ./python venv/bin/python -m soma.tests
```
