### ISSUE TITLE
inspect.getargspec has disappeared in python 3.11

### ISSUE THREAD

**Issue by servoz** [populse/soma-base#31]
```
% python3
Python 3.9.9 (main, Nov 19 2021, 00:00:00) 
[GCC 10.3.1 20210422 (Red Hat 10.3.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import inspect
>>> inspect.getargspec
<function getargspec at 0x7fecff0cd430>
>>> inspect.getfullargspec
<function getfullargspec at 0x7fecff0cd940>
```
So:
```
>>> getfullargspec = getattr(inspect, 'getfullargspec', inspect.getargspec)
>>> getfullargspec
<function getfullargspec at 0x7fecff0cd940>
```

```
$ python
Python 3.11.2 (main, Feb  8 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import inspect
>>> inspect.getfullargspec
<function getfullargspec at 0x7f5d30a03600>
>>> inspect.getargspec
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?

```
So:
```
>>> getfullargspec = getattr(inspect, 'getfullargspec', inspect.getargspec)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?

```

And [we use `getfullargspec = getattr(inspect, 'getfullargspec', inspect.getargspec)` in soma-base](https://github.com/populse/soma-base/blob/master/python/soma/utils/functiontools.py#L49) ...

**Comment by servoz** [comment]
```
$ python
Python 3.11.2 (main, Feb  8 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import inspect
>>> getfullargspec = getattr(inspect, 'getfullargspec', getattr(inspect, 'getargspec'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?

```
Can we instead consider?:
```
getfullargspec = getattr(inspect, 'getfullargspec', getattr(inspect, 'getargspec', None))
if getfullargspec is None:
    foo
```

**Comment by denisri** [comment]
Yes you're right. I couldn't really test, I don't have python 3.11 installed. I'm fixing it.

**Comment by servoz** [comment]
Lovely !!! Thanks a lot @denisri .
